[build]
  base = "/"
  publish = "frontend/build/"
  command = "npm run build:plugins:prod && npm run build:frontend"

[template.environment]
  NODE_ENV = "production"  
  NODE_VERSION = "14.21.1"
  NPM_VERSION = "7.20.0"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200