version: '3'

services:
  tooljet:
    image: tooljet/tooljet-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000:80
    env_file: .env
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgres_data
