name: Add issue to GitHub project on roadmap label

on:
  issues:
    types: [labeled]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is roadmap
        run: |
          if [ "${{ github.event.label.name }}" = "roadmap" ]; then
            echo "Issue added to project"
            exit 0
          else
            echo "Label is not roadmap, exiting..."
            exit 1
          fi

      - name: Fetch issues with roadmap label
        id: fetch-issues
        uses: peter-evans/find-labeled-prs@v2
        with:
          label: 'roadmap'
          state: 'open'
          repo-token: ${{ secrets.GITHUB_TOKEN }}     

      - name: Add issue to GitHub project
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          labels: ${{ github.event.issue.labels }}
          project-name: testing-project
          column-name: To do
          assignees: ${{ github.event.issue.assignees }}
          milestone: ${{ github.event.issue.milestone }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
